root = "."
tmp_dir = "tmp"

[build]
  entrypoint = "."
  cmd = "npx postcss web/static/input.css -o web/static/tailwind.css && go build -o tmp/bedwetter ."
  delay = 500
  exclude_dir = ["tmp", "web/static"]
  exclude_file = []
  exclude_regex = [".*_test.go"]
  exclude_unchanged = false
  full_bin = "./tmp/bedwetter -config config.yaml"
  include_dir = []
  include_ext = ["go", "html", "yaml", "yml"]
  kill_delay = "2s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "green"
  runner = "cyan"
  watcher = "blue"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
